# # docker-compose.yml
# version: '3.8'

# services:
#   web:
#     build: .
#     volumes:
#       - .:/app
#     working_dir: /app
#     # environment:
#     #   - DJANGO_SETTINGS_MODULE=bookstore_project.settings  # Changed from bookstore_project.settings
#     #   - PYTHONPATH=/app  # Add this to ensure Python can find your modules
#     command: python manage.py runserver 0.0.0.0:8000


version: '3.8'

services:
  web:
    build: .
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "8000:8000"        # ← add this line
    command: python manage.py runserver 0.0.0.0:8000
